In [18]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.72185051 0.0813029  0.20847016]
  [0.44239662 0.68053863 0.78996723]
  [0.47765089 0.2469447  0.35921681]]

 [[0.46891511 0.56328267 0.28427656]
  [0.32672663 0.09320781 0.52066266]
  [0.03352182 0.25721694 0.67289189]]

 [[0.28301661 0.76105731 0.61165175]
  [0.91760995 0.19794943 0.83401442]
  [0.87008493 0.849268   0.60464926]]]


In [17]:
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [16]:
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [15]:
x= np.random.random((3,3))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.89524066 0.7836238  0.0997304 ]
 [0.69606883 0.88045378 0.09034118]
 [0.30240206 0.4889941  0.50104819]]
After normalization:
[[1.         0.8613282  0.01166508]
 [0.75255068 0.98162891 0.        ]
 [0.26346256 0.49528286 0.51025876]]


In [14]:
array1 = np.array([0, 10, 20, 40, 70])
print("Array1: ",array1)
array2 = [10, 30, 40,70]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 70]
Array2:  [10, 30, 40, 70]
Common values between two arrays:
[10 40 70]


In [13]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-11-24
Today:  2020-11-25
Tomorrow:  2020-11-26


In [12]:
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[1 0 1 1 0 1]
Second array:
[0 0 0 1 1 1]
Test above two arrays are equal or not!
False


In [11]:
x = np.random.random(15)
print("Original array:")
print(x)
x[x.argmax()] = -1
print("Maximum value replaced by -1:")
print(x)

Original array:
[0.1879857  0.59081972 0.06909839 0.78996151 0.44030889 0.45965787
 0.76983244 0.23256768 0.31544653 0.44431499 0.37544149 0.04491665
 0.11450737 0.69994695 0.57434404]
Maximum value replaced by -1:
[ 0.1879857   0.59081972  0.06909839 -1.          0.44030889  0.45965787
  0.76983244  0.23256768  0.31544653  0.44431499  0.37544149  0.04491665
  0.11450737  0.69994695  0.57434404]


In [10]:
np.set_printoptions(threshold=np.inf)
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.83914237 0.25927596 0.24181626 0.54106215 0.34982062 0.84074897
  0.05705279 0.01285649 0.29002573 0.95864584]
 [0.97780232 0.45979226 0.46401916 0.71733953 0.10035026 0.11880061
  0.19637238 0.15962463 0.92130841 0.16864352]
 [0.35199892 0.05597943 0.66551347 0.23973194 0.87602681 0.9853074
  0.00550662 0.59788363 0.52595073 0.09695448]
 [0.09219809 0.59247209 0.45387936 0.31413327 0.01401731 0.36473982
  0.42825993 0.82839783 0.87196154 0.70424788]
 [0.6731393  0.81556947 0.63050636 0.90409856 0.80761229 0.20803619
  0.9515256  0.56735771 0.06933264 0.34879567]]

Subtract the mean of each row of the said matrix:

[[ 0.40009766 -0.17976876 -0.19722846  0.10201743 -0.0892241   0.40170425
  -0.38199193 -0.42618823 -0.14901898  0.51960112]
 [ 0.54939701  0.03138695  0.03561386  0.28893422 -0.32805505 -0.3096047
  -0.23203293 -0.26878068  0.49290311 -0.25976178]
 [-0.08808642 -0.38410591  0.22542812 -0.2003534   0.43594146  0.54522206
  -0.43457872  0.15779829  0.085

In [8]:
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)


In [7]:
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


In [6]:
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[3 4 1 5 3 2 2 6 2 5 4 4 3 7 1 5 0 8 1 9 3 9 1 3 8 6 6 6 0 6 6 6 7 2 9 2 2
 4 4 0]
Most frequent value in the above array:
6


In [5]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
np.diag(np.dot(A, B))
np.sum(A * B.T, axis=1)
np.einsum("ij,ji->i", A, B)

array([68, 14, 17])

In [4]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 1. 1. 2. 3. 3. 2. 5. 6. 4.]
